BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "kairos"
BBFILE_PATTERN_kairos = "^${LAYERDIR}/"
BBFILE_PRIORITY_kairos = "10"

LAYERDEPENDS_kairos = "core openembedded-layer"
LAYERSERIES_COMPAT_kairos = "stylish"
